SHOW databases;
USE ORG;
SHOW TABLES;

-- HOW TO INSERT THE DATA IN THE TABLE
CREATE TABLE CUSTOMER(
ID INT PRIMARY KEY,
CUS_NAME VARCHAR(255),
ADDRESS VARCHAR(255),
GENDER CHAR(2),
CITY VARCHAR(50),
PINCODE INTEGER);

DESC CUSTOMER;