SHOW databases;
USE ORG;
SHOW TABLES;

-- HOW TO INSERT THE DATA IN THE TABLE
CREATE TABLE CUSTOMER(
ID INT PRIMARY KEY,
CUS_NAME VARCHAR(255),
ADDRESS VARCHAR(255),
GENDER CHAR(2),
CITY VARCHAR(50),
PINCODE INTEGER);

DESC CUSTOMER;

-- ADDING NEW COLUMN
DESC ACCOUNT_DETAILS;
ALTER TABLE ACCOUNT_DETAILS ADD INTEREST FLOAT NOT NULL default 0;
SELECT *FROM ACCOUNT_DETAILS;

-- MODIFY COLUMN
ALTER TABLE ACCOUNT_DETAILS MODIFY INTEREST DOUBLE NOT NULL DEFAULT 0;
DESC ACCOUNT_DETAILS; 

-- RENAME THE COLUMN( CHANGE COLUMN)
ALTER TABLE ACCOUNT_DETAILS CHANGE COLUMN INTEREST SAVING_ACCOUNT FLOAT NOT NULL DEFAULT 0; -- WE HAVE TO TELL THE DATA TYPE ALSO
DESC ACCOUNT_DETAILS;

-- DROP COLUMN
ALTER TABLE ACCOUNT_DETAILS DROP COLUMN SAVING_ACCOUNT;
DESC ACCOUNT_DETAILS;

-- RENAME THE TABLE
ALTER TABLE ACCOUNT_DETAILS RENAME TO ACCOUNT_INFO;
DESC ACCOUNT_INFO;