USE ORG;
SHOW TABLES;
SELECT * FROM CUSTOMER;
DESC customer;


-- HOW TO INSERT THE DATA
INSERT INTO customer(ID,CUS_NAME,ADDRESS,GENDER,CITY,PINCODE)
VALUES(1001,'ADITYA','JAIPUR','M','JAIPUR',302012);

INSERT INTO CUSTOMER VALUES(1002,'AKSHIT','JAIPUR','M','JAIPUR',302012);

-- IF I HAVE FEW AVAILABLE THINGS
INSERT INTO CUSTOMER(ID,CUS_NAME)
VALUES(1003,'RAJ');
SELECT * FROM CUSTOMER;

-- HOW TO UPDATE THE TABLE
UPDATE CUSTOMER SET ADDRESS ='GOVINDPURA', GENDER='M',CITY='JAIPUR',PINCODE = 302012 WHERE ID = 1003;
SELECT *FROM CUSTOMER;

-- UPDATE MULTIPLE ROWS
SET SQL_SAFE_UPDATES = 1; -- MAKE IT 0 TO AFFTECT 
UPDATE CUSTOMER SET PINCODE =111111;
SELECT *FROM CUSTOMER;

-- delete
DELETE FROM CUSTOMER WHERE ID = 1003;
SELECT * FROM CUSTOMER;
DELETE FROM customer;

-- ON DELETE CASCADE

CREATE TABLE ORDER_DETAILS(ORDER_ID INT PRIMARY KEY,
DELIVERY_DATE DATE,
CUST_ID INT,
FOREIGN KEY (CUST_ID) REFERENCES CUSTOMER(ID));
DESC ORDER_DETAILS;
INSERT INTO ORDER_DETAILS(ORDER_ID,DELIVERY_DATE,CUST_ID)VALUES(101,'2026-08-20',1001);
SELECT* FROM ORDER_DETAILS;

DELETE FROM customer WHERE ID =1001; -- WE CANNOT DELETE LIKE THIS
SHOW CREATE TABLE ORDER_DETAILS; -- TO GET THE FOREIGN KEY RELATION

ALTER TABLE ORDER_DETAILS DROP foreign key ORDER_DETAILS_IBFK_1; -- TO REMOVE THE FOREIGN KEY CONSTRAINTS
DESC ORDER_DETAILS;
-- NOW WE WILL CHANGE IT
ALTER TABLE ORDER_DETAILS ADD FOREIGN KEY(CUST_ID) REFERENCES CUSTOMER(ID) ON DELETE CASCADE;

INSERT INTO ORDER_DETAILS(ORDER_ID,DELIVERY_DATE,CUST_ID)
VALUES(1002,'2026-8-12',1001);
SELECT *FROM ORDER_DETAILS;
delete FROM CUSTOMER WHERE ID = 1001;
SELECT *FROM ORDER_DETAILS;
SELECT *FROM CUSTOMER;


-- ON DELTE SET NULL
ALTER TABLE ORDER_DETAILS DROP FOREIGN KEY ORDER_DETAILS_IBFK_1;
DESC ORDER_DETAILS;
ALTER TABLE ORDER_DETAILS ADD FOREIGN KEY(CUST_ID) REFERENCES CUSTOMER(ID) ON DELETE SET NULL;
DESC ORDER_DETAILS;
INSERT INTO ORDER_DETAILS(ORDER_ID,DELIVERY_DATE,CUST_ID)
VALUES(1001,'2025-08-12',1002);
SELECT *FROM ORDER_DETAILS;
DELETE FROM CUSTOMER WHERE ID = 1002;
SELECT * FROM ORDER_DETAILS;


-- REPLACE (REQUIRES PRIMARY KEY)
REPLACE INTO CUSTOMER(ID,CUS_NAME)VALUES(1002,'PRANEET'); -- OTHER VALUES WILL BE AUTOMATICALLY SET NULL
SELECT *FROM CUSTOMER;
REPLACE INTO CUSTOMER(ID,CUS_NAME)VALUES(1003,'TUSHAR');
REPLACE INTO CUSTOMER SET ID =1002,CUS_NAME = 'RAHUL',CITY='KOTA'; -- ANOTHER METHOD 
REPLACE INTO CUSTOMER (ID,CUS_NAME)
SELECT ID,CUS_NAME FROM CUSTOMER WHERE ID=1002;
SELECT *FROM CUSTOMER;





