SHOW databases;
USE ORG;

CREATE TABLE EMPLOYEE(EMPID INT primary KEY, FNAME VARCHAR(30),LNAME VARCHAR(30), AGE INT, EMAIL_ID VARCHAR(30),PHONE INT,CITY VARCHAR(12)); 
CREATE TABLE PROJECT(PID INT PRIMARY KEY,EMPID INT,NAME VARCHAR(30),START_DATE DATE,CLIENTID INT,FOREIGN KEY(CLIENTID) REFERENCES CLIENT(CLIENTID));
CREATE TABLE CLIENT(CLIENTID INT PRIMARY KEY,FNAME VARCHAR(30),LNAME VARCHAR(30),AGE INT,EMAIL_ID VARCHAR(30),PHONE INT,CITY VARCHAR(12),EMPID INT,FOREIGN KEY(EMPID) REFERENCES EMPLOYEE(EMPID));
ALTER TABLE PROJECT add constraint fk_project_client FOREIGN KEY(clientid)  REFERENCES CLIENT(CLIENTID);
SELECT *FROM CLIENT;

INSERT INTO EMPLOYEE VALUES
(101, 'Rahul', 'Sharma', 25, 'rahul@gmail.com', 987654321, 'Chennai'),
(102, 'Priya', 'Patel', 28, 'priya@gmail.com', 987654322, 'Mumbai'),
(103, 'Arjun', 'Kumar', 24, 'arjun@gmail.com', 987654323, 'Delhi'),
(104, 'Sneha', 'Reddy', 27, 'sneha@gmail.com', 987654324, 'Hyderabad'),
(105, 'Vikram', 'Singh', 30, 'vikram@gmail.com', 987654325, 'Pune'),
(106, 'Ananya', 'Iyer', 26, 'ananya@gmail.com', 987654326, 'Bangalore'),
(107, 'Karan', 'Mehta', 29, 'karan@gmail.com', 987654327, 'Ahmedabad'),
(108, 'Neha', 'Gupta', 23, 'neha@gmail.com', 987654328, 'Kolkata');

INSERT INTO CLIENT VALUES
(201, 'Amit', 'Verma', 35, 'amit@gmail.com', 900000001, 'Chennai', 101),
(202, 'Riya', 'Malhotra', 32, 'riya@gmail.com', 900000002, 'Mumbai', 102),
(203, 'Suresh', 'Nair', 40, 'suresh@gmail.com', 900000003, 'Delhi', 103),
(204, 'Pooja', 'Shah', 29, 'pooja@gmail.com', 900000004, 'Pune', 104),
(205, 'Raj', 'Kapoor', 45, 'raj@gmail.com', 900000005, 'Hyderabad', 105),
(206, 'Meena', 'Joshi', 38, 'meena@gmail.com', 900000006, 'Bangalore', 106);

INSERT INTO PROJECT VALUES
(301, 101, 'Banking System', '2025-01-15', 201),
(302, 102, 'E-Commerce App', '2025-02-10', 202),
(303, 103, 'Hospital System', '2025-03-20', 203),
(304, 104, 'Inventory System', '2025-04-05', 204),
(305, 105, 'Payment System', '2025-05-12', 205),
(306, 106, 'Learning Platform', '2025-06-18', 206),
(307, 101, 'CRM System', '2025-07-01', 202),
(308, 103, 'Mobile Banking', '2025-08-10', 201);

INSERT INTO PROJECT(PID,EMPID,NAME,START_DATE)VALUES(309,103,'LMS','2025-04-12');
-- INNER JOIN
SELECT E.EMPID,E.FNAME,E.LNAME,P.PID,P.NAME FROM EMPLOYEE AS E
INNER JOIN PROJECT AS P ON E.EMPID=P.EMPID;
SELECT E.EMPID,E.FNAME,E.LNAME,P.PID,P.NAME FROM EMPLOYEE AS E,PROJECT AS P WHERE E.EMPID=P.EMPID;

-- FETCH OUT ALL THE  EMPLOYEE ID'S AND THEIR CONTACT DETAILS WHO HAVE BEEN WORKING FROM pune WITH THE CLIENT NAME WORKING IN hyderabad
SELECT E.EMPID,E.EMAIL_ID,E.PHONE,C.FNAME,C.LNAME FROM EMPLOYEE AS E INNER JOIN CLIENT AS C ON E.EMPID = C.EMPID WHERE E.CITY = 'PUNE' AND C.CITY = 'HYDERABAD';

-- LEFT JOIN
-- FETCH OUT EACH PROJECT ALLOCATED TO EACH EMPLOYEE
SELECT * FROM PROJECT AS P LEFT JOIN EMPLOYEE AS E ON E.EMPID=P.EMPID;

-- RIGHT JOIN
-- LIST OUT ALL THE PROJECTS ALONG WITH THE EMPLOYEE'S NAME AND THEIR RESPECTIVE ALLOCATED EMAIL ID
SELECT P.NAME,P.PID,E.FNAME,E.LNAME,E.EMAIL_ID FROM EMPLOYEE AS E RIGHT JOIN PROJECT AS P ON E.EMPID = P.EMPID;

-- CROSS JOIN
-- LIST OUT ALL THE COMBINATIONS FOR THE EMPLOYEE'S NAME AND PROJECTS THAT CAN EXISTS;
SELECT E.FNAME,E.LNAME,P.NAME,P.PID FROM EMPLOYEE AS E CROSS JOIN PROJECT AS  P;




-- SET OPERATIONS

CREATE TABLE DEPARTMENT1(EMPID INT,NAME VARCHAR(20),ROLE VARCHAR(20));
CREATE TABLE DEPARTMENT2(EMPID INT, NAME VARCHAR(20),ROLE VARCHAR(20));
INSERT INTO DEPARTMENT1(EMPID,NAME,ROLE)
VALUES(101,'ADITYA','BACKEND'),
(102,'AKSHIT','ANDROID'),
(103,'SHAURYA','DEVELOPMENT');

INSERT INTO DEPARTMENT2(EMPID,NAME,ROLE)
VALUES(100,'ANIL','SALESMAN'),
(104,'SUNIL','SALESMAN'),
(99,'SUNIL','BACKEND');

INSERT INTO DEPARTMENT2(EMPID,NAME,ROLE)
VALUES(101,'ADITYA','BACKEND');
-- UNION
-- LIST OUT ALL THE EMPLOYEE IN THE COMPANY
SELECT * FROM DEPARTMENT1 UNION SELECT *FROM DEPARTMENT2;

-- lIST OUT ALL THE EMPLOYEES IN ALL THE DEPARTMENT WHO WORKS AS SALESMAN

SELECT * FROM DEPARTMENT1 WHERE ROLE = 'SALESMAN'
UNION 
SELECT * FROM DEPARTMENT2 WHERE ROLE = 'SALESMAN';


--	LIST OUT ALL THE EMPLOYEES WHO WORK IN BOTH THE DEPATMENT;
-- INTERSECTION
SELECT DEPARTMENT1.* FROM DEPARTMENT1 INNER JOIN DEPARTMENT2 USING(EMPID);

-- LIST OUT ALL THE EMPLOYEES WORKING IN DEPARTMENT1 BUT NOT IN DEPARTMENT 2;
-- MINUS
SELECT * FROM DEPARTMENT1 LEFT JOIN DEPARTMENT2 USING(EMPID) WHERE DEPARTMENT2.EMPID IS NULL;
	
