show databases;
use org;
show tables;
select *from employee;
-- SUB QUERIES;
select * from employee where age in (select age from employee where age >25);

-- find employees who are assigned to more than one project
select * FROM EMPLOYEE WHERE EMPID IN (SELECT EMPID FROM PROJECT GROUP BY EMPID HAVING COUNT(EMPID)>1);
 
 -- SINGLE VALUE SUBQUERY
 SELECT AVG(AGE) FROM EMPLOYEE;
 -- EMPLOYEES HAVING GREATER AGE THAN AVERAGE
SELECT * FROM EMPLOYEE WHERE AGE>( SELECT AVG(AGE) FROM EMPLOYEE);

-- FROM CLAUSE
-- SELECT MAX AGE PERSON  WHOSE FIRST NAME CONTAINS 'A' -- DERIVED TABLES
SELECT MAX(AGE) FROM (SELECT * FROM EMPLOYEE WHERE FNAME LIKE 'A%') AS TEMP;


-- CORELATED QUERIES
-- FIND OUT 3RD LARGEST EMPLOYEE
SELECT * FROM EMPLOYEE AS E1 WHERE 3 = (SELECT COUNT(E2.AGE) FROM EMPLOYEE AS E2  WHERE E2.AGE>=E1.AGE);
SELECT *FROM EMPLOYEE;

-- SQL VIEW
SELECT * FROM EMPLOYEE;
-- CREATING A VIEW
CREATE VIEW CUSTOM_VIEW AS SELECT FNAME,AGE FROM EMPLOYEE;
-- VIEWING FROM VIEW
SELECT *FROM CUSTOM_VIEW;

-- ALTER VIEW 
ALTER VIEW CUSTOM_VIEW AS SELECT FNAME,LNAME,AGE FROM EMPLOYEE;
SELECT *FROM CUSTOM_VIEW;

-- DROP VIEW
DROP VIEW IF EXISTS CUSTOM_VIEW;
